version: '3'

services:
  ghidra:
    build:
      context: .
      dockerfile: Dockerfile-ghidra-dev
    environment:
      - DEV=true
    volumes:
      - "./ghidra/bridge:/opt/ghidra/bridge"
  webapp:
    build:
      context: .
      dockerfile: Dockerfile-webapp-dev
    depends_on:
      - ghidra
    volumes:
      - './webapp:/app'
      - /app/node_modules
      - /app/dist
    environment:
      - NODE_ENV=dev
    command: bash -c "{ yarn install --force --frozen-lockfile && (yarn serve --port 8080) }"
    ports:
      - "8080:8080"
