version: '3.4'

services:
  ghidra:
    build:
      context: .
      target: ghidra-dev
    environment:
      - GHIDRA_IP=${GHIDRA_IP}
    ports: 
      - "13100:13100"
      - "13101:13101"
      - "13102:13102"
