version: '3'

services:
  ghidra:
    build:
      context: .
    hostname: whidra.hats.sg
    environment:
      - GHIDRA_PASS=changeme
    ports:
      - "13100:13100"
      - "13101:13101"
      - "13102:13102"
      - "8000:8000"
