version: '3'

services:
  ghidra:
    build: ./ghidra
    container_name: pwnbro_ghidra
    network_mode: host
    hostname: whidra.hats.sg
    volumes:
      - "main:/data"
    ports:
      - "13100:13100"
      - "13101:13101"
      - "13102:13102"
  app:
    build: ./app
    container_name: pwnbro_app
    networks:
      - main
    volumes:
      - "main:/data"
    ports:
      - "8080:3000"
    depends_on:
      - ghidra

volumes:
  main:

networks:
  main:
