micronaut:

  security:
    authentication: cookie
    token:
      jwt:
        cookie:
          cookie-name: AUTHENTICATION
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
              jws-algorithm: HS256

    intercept-url-map:
      -
        pattern: /redoc/*
        http-method: GET
        access:
          - isAnonymous()
      -
        pattern: /swagger/*
        http-method: GET
        access:
          - isAnonymous()
      -
        pattern: /swagger-ui/*
        http-method: GET
        access:
          - isAnonymous()
      -
        pattern: /rapidoc/*
        http-method: GET
        access:
          - isAnonymous()
    endpoints:
      login:
        path: /auth/login
      logout:
        path: /auth/logout

  session:
    http:
      cookie-max-age: 5m
      header-names:
        - X-Session
        - X-Session-Token
        - Session-Info

  io:
    watch:
      paths: src/main
      restart: true

  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
